services:
  app:
    image: wisdomwork/ecode:latest
    platform: linux/x86_64
    ports:
      - '4000:4000'
    expose:
      - '4000'
    restart: always
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
