services:
  app:
    image: wisdomwork/ecode:latest
    platform: linux/amd64
    ports:
      - '4000:4000'
    restart: always
    args:
      - VITE_API_URL=${VITE_API_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
